from .loss import categorical_corssentropy_with_label_gt
from .loss import gen_disc_regular_loss1
from .loss import gen_disc_regular_loss2
from .loss import gen_disc_wgan_loss
from .loss import disc_ext_regular_loss1
from .loss import disc_ext_regular_loss2
from .loss import disc_ext_wgan_loss
from .loss import disc_ext_wgan_gp_loss
from .loss import softplus_non_sat_loss
from .loss import softplus_loss
from .loss import r_penalty_loss
from .loss import softplus_non_sat_r_penalty_loss

from .loss import CategoricalCrossentropyWithLabelGT
from .loss import GenDiscRegularLoss1
from .loss import GenDiscRegularLoss2
from .loss import GenDiscWGANLoss
from .loss import DiscExtRegularLoss1
from .loss import DiscExtRegularLoss2
from .loss import DiscExtWGANLoss
from .loss import DiscExtWGANGPLoss
from .loss import SoftPlusNonSatLoss
from .loss import SoftPlusLoss
from .loss import RPenaltyLoss
from .loss import SoftPlusNonSatRPenaltyLoss
